### ISSUE TITLE
Solution is not correct. 

### ISSUE THREAD

**Issue by AndreyNeyvanov** [thereal1024/python-md5-collision#1]
All output files have the same content. Consequently md5 sums are the same.
In cryptography, a collision attack on a cryptographic hash tries to find two inputs producing the same hash value, i.e. a hash collision.
See https://en.wikipedia.org/wiki/Collision_attack

**Comment by vitenbergd** [comment]
First of all @thereal1024 thx a lot for your work!

@AndreyNeyvanov  - nope, solution is indeed correct and i guess you should avoid false assumptions without any attempt to prove your words. And also author even provided instructions to check all generated files:

**gen_coll_python.py**
```
md5sum out_py_good.py out_py_evil.py
e82979117a1f420c25d83b64ca02ce18  out_py_good.py
e82979117a1f420c25d83b64ca02ce18  out_py_evil.py


sha256sum out_py_good.py out_py_evil.py
827d408d00fcf4858808b1784faa29d5fbf5ae1eb94c8988b43ce00cb16c9a48  out_py_good.py
a85cf4e9c1bf747f1d44e73b6396b636963da8e5819ba2867043b60248a64755  out_py_evil.py
```

**gen_coll_c.py**
```
sha256sum out_c_good out_c_evil
33d8fbfc6f176d2339f62dc7ae84061543b3be745e78ff22e7830be53ced6820  out_c_good
9028bd9b362ca5632619e9e32e52a589639f9ebb2cfa0918b68772c0638e91bc  out_c_evil

md5sum out_c_good out_c_evil
04afcf2d4c0d5f853f6325ea3e7b64fe  out_c_good
04afcf2d4c0d5f853f6325ea3e7b64fe  out_c_evil
```
So, i guess it's obvious that non affected hash functions will give you different results.

And btw you can use other *nix tools  to check the difference:
```
cmp -b out_c_evil out_c_good
out_c_evil out_c_good differ: byte 8276, line 3 is  12 ^J 212 M-^J

diff -qs out_c_evil out_c_good
Binary files out_c_evil and out_c_good differ

cmp -b out_py_evil.py out_py_good.py
out_py_evil.py out_py_good.py differ: byte 84, line 4 is 266 M-6  66 6

diff -qs out_py_good.py out_py_evil.py
Files out_py_good.py and out_py_evil.py differ
```

**Comment by laliB-gniK** [comment]
hey i'm getting this error any fixes?


traceback (most recent call last):
  File "./gen_coll_test.py", line 14, in <module>
    c.diverge()
  File "coll.py", line 145, in diverge
    b0, b1 = collide(self.digester.ihv())
  File "coll.py", line 79, in collide
    with open(f0, 'rb') as f0d:
FileNotFoundError: [Errno 2] No such file or directory: 'out-516f6b7ad93ff1a3c79259cbbf018d7e-0'
